package Login;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author david
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TituloInicioSesion = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        TituloUsuario1 = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TituloContraseña = new javax.swing.JLabel();
        ContraseñaText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        BotonIngresar1 = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/imagenes/appLogotipo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 360, 500));

        TituloInicioSesion.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        TituloInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloInicioSesion.setText(" Inicio de Sesión");
        TituloInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TituloInicioSesion.setDoubleBuffered(true);
        TituloInicioSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TituloInicioSesion.setName(""); // NOI18N
        jPanel1.add(TituloInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 270, 50));
        TituloInicioSesion.getAccessibleContext().setAccessibleName("Iniciar  Sesión");
        TituloInicioSesion.getAccessibleContext().setAccessibleDescription("Texto inicio sesion");
        TituloInicioSesion.getAccessibleContext().setAccessibleParent(TituloInicioSesion);

        botonRegistrar.setText("Registrarse");
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
        });
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        TituloUsuario1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TituloUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloUsuario1.setText("Usuario");
        jPanel1.add(TituloUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 20));

        UsuarioText.setBackground(new java.awt.Color(51, 51, 51));
        UsuarioText.setForeground(new java.awt.Color(102, 102, 102));
        UsuarioText.setText("Ingrese su Usuario");
        UsuarioText.setBorder(null);
        UsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextActionPerformed(evt);
            }
        });
        jPanel1.add(UsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 330, 20));

        jSeparator1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 330, 10));

        TituloContraseña.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TituloContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloContraseña.setText("Contraseña");
        jPanel1.add(TituloContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 70, 20));

        ContraseñaText.setBackground(new java.awt.Color(51, 51, 51));
        ContraseñaText.setForeground(new java.awt.Color(102, 102, 102));
        ContraseñaText.setText("Ingrese su Contraseña");
        ContraseñaText.setBorder(null);
        ContraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 330, 20));

        jSeparator2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 330, 10));

        BotonIngresar1.setText("Ingresar");
        BotonIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        jPanel1.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void ContraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextActionPerformed

    private void UsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextActionPerformed

    private void BotonIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresar1ActionPerformed

        try {
            FileInputStream file = new FileInputStream("src/test/BD.xlsx");
            Workbook libro = new XSSFWorkbook(file);
            Sheet hojas = libro.getSheetAt(0);
            Row filas;
            String valor1 = "";
            String valor2 = "";
            for (Row fila : hojas) {
                for (Cell celda : fila) {
                    if (celda.getRowIndex() == 0 && celda.getColumnIndex() == 0) {
                        valor1 = celda.getStringCellValue();
                    } else if (celda.getRowIndex() == 1 && celda.getColumnIndex() == 0) {
                        valor2 = celda.getStringCellValue();
                    }

                }
            }
            if (valor1.equals(UsuarioText.getText()) && valor2.equals(ContraseñaText.getText())) {
                mensaje.setText("Inicio exitoso");
            } else {
                mensaje.setText("Usuario no encontraso, verifique los datos o registrese");
            }

            //cerramos el libro
            libro.close();

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_BotonIngresar1ActionPerformed

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        Registro registro = new Registro();
        registro.setVisible(true);
    }//GEN-LAST:event_botonRegistrarMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar1;
    private javax.swing.JTextField ContraseñaText;
    private javax.swing.JLabel TituloContraseña;
    private javax.swing.JLabel TituloInicioSesion;
    private javax.swing.JLabel TituloUsuario1;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
