package Login;

import java.text.ParseException;
import com.mycompany.proyectojpoo.Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloRegistro = new javax.swing.JLabel();
        tituloNombre = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tituloRut = new javax.swing.JLabel();
        rutUsuario = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TituloFecha = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        tituloCorreo = new javax.swing.JLabel();
        correoUsuario = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        tituloContrasena = new javax.swing.JLabel();
        Contrasena = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        tituloConfirmacionContrasena = new javax.swing.JLabel();
        confirmacionContrasena = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        botonRegistrar = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloRegistro.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        TituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloRegistro.setText("Registro de Usuario");
        TituloRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TituloRegistro.setDoubleBuffered(true);
        TituloRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TituloRegistro.setName(""); // NOI18N
        getContentPane().add(TituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, 50));

        tituloNombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tituloNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloNombre.setText("Nombre");
        getContentPane().add(tituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 20));

        nombreUsuario.setBackground(new java.awt.Color(51, 51, 51));
        nombreUsuario.setForeground(new java.awt.Color(102, 102, 102));
        nombreUsuario.setText("Ingrese su nombre");
        nombreUsuario.setBorder(null);
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 330, 20));

        jSeparator1.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 330, 10));

        tituloRut.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tituloRut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloRut.setText("Rut");
        getContentPane().add(tituloRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 70, 20));

        rutUsuario.setBackground(new java.awt.Color(51, 51, 51));
        rutUsuario.setForeground(new java.awt.Color(102, 102, 102));
        rutUsuario.setText("Ingrese su rut");
        rutUsuario.setToolTipText("");
        rutUsuario.setBorder(null);
        rutUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(rutUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 330, 20));

        jSeparator7.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 330, 10));

        TituloFecha.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TituloFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TituloFecha.setText("Fecha de nacimiento");
        getContentPane().add(TituloFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 160, 20));

        fechaNacimiento.setBackground(new java.awt.Color(51, 51, 51));
        fechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        fechaNacimiento.setText("dd/mm/aaaa");
        fechaNacimiento.setBorder(null);
        fechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 330, 20));

        jSeparator8.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 330, 10));

        tituloCorreo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tituloCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloCorreo.setText("Correo Electronico");
        getContentPane().add(tituloCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 120, 20));

        correoUsuario.setBackground(new java.awt.Color(51, 51, 51));
        correoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        correoUsuario.setText("Ingrese su correo");
        correoUsuario.setBorder(null);
        correoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(correoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 330, 20));

        jSeparator9.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 330, 10));

        tituloContrasena.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tituloContrasena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloContrasena.setText("Contraseña");
        getContentPane().add(tituloContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, 20));

        Contrasena.setBackground(new java.awt.Color(51, 51, 51));
        Contrasena.setForeground(new java.awt.Color(102, 102, 102));
        Contrasena.setText("Ingrese su contraseña");
        Contrasena.setBorder(null);
        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 330, 20));

        jSeparator10.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 330, 10));

        tituloConfirmacionContrasena.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tituloConfirmacionContrasena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloConfirmacionContrasena.setText("Contraseña");
        getContentPane().add(tituloConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 70, 20));

        confirmacionContrasena.setBackground(new java.awt.Color(51, 51, 51));
        confirmacionContrasena.setForeground(new java.awt.Color(102, 102, 102));
        confirmacionContrasena.setText("Confirme su contraseña");
        confirmacionContrasena.setBorder(null);
        confirmacionContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmacionContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(confirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 330, 20));

        jSeparator11.setBackground(new java.awt.Color(153, 255, 204));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 330, 10));

        botonRegistrar.setText("Registrarse");
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
        });
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        Usuario user = new Usuario();

        try{
            // TODO add your handling code here:
            Date fechaNacimiento = null;
            fechaNacimiento = new SimpleDateFormat("dd/mm/yyyy").parse(fechaNacimiento.toString());
            if (Contrasena.getText().equals(confirmacionContrasena)) {
                user.setRut(rutUsuario.getText());
                user.setName(nombreUsuario.getText());
                user.setFechaNacimiento(fechaNacimiento);
                user.setEmail(correoUsuario.getText());
                user.setPassword(Contrasena.getText());

                mensaje.setText("Datos creados");
            }
            else
                mensaje.setText("Las contraseñas no coinciden");
        }catch(ParseException ex){
            mensaje.setText("error en el registro");
        }


    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void rutUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutUsuarioActionPerformed

    private void fechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoActionPerformed

    private void correoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoUsuarioActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void confirmacionContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmacionContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmacionContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contrasena;
    private javax.swing.JLabel TituloFecha;
    private javax.swing.JLabel TituloRegistro;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField confirmacionContrasena;
    private javax.swing.JTextField correoUsuario;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JTextField rutUsuario;
    private javax.swing.JLabel tituloConfirmacionContrasena;
    private javax.swing.JLabel tituloContrasena;
    private javax.swing.JLabel tituloCorreo;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloRut;
    // End of variables declaration//GEN-END:variables
}
